FROM ubuntu:16.04

RUN apt-get update && apt-get install -y python python-dev gcc \
    python-pip python-setuptools
ADD trip_ranking /app
WORKDIR /app
RUN pip install -r requirements.txt & pip install uwsgi
CMD uwsgi --http :5000 --master --processes 4 --wsgi-file app.py
EXPOSE 5000